<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Jadwal_model extends CI_Model
{

    public $table = 'tbl_detail_jadwal';
    public $id = 'id_jadwal';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('tbl_detail_jadwal.id_jadwal,tbl_detail_jadwal.hari,tbl_detail_jadwal.nip, tbl_guru.nama_guru,tbl_detail_jadwal.kode_kelas,tbl_mapel.mapel,tbl_detail_jadwal.jam_mulai,tbl_detail_jadwal.jam_selesai');
        $this->datatables->from('tbl_detail_jadwal');
     //  $this->datatables->add_column('is_aktif', '$1', 'rename_string_is_aktif(is_aktif)');
        //add this line for join
        $this->datatables->join('tbl_guru', 'tbl_guru.nip=tbl_detail_jadwal.nip');
         $this->datatables->join('tbl_kelas','tbl_kelas.kode_kelas=tbl_detail_jadwal.kode_kelas');
         $this->datatables->join('tbl_mapel','tbl_mapel.kode_mapel=tbl_detail_jadwal.kode_mapel');
        $this->datatables->add_column('action',anchor(site_url('jadwal/update/$1'),'<i class="fa fa-pencil-square-o" aria-hidden="true"></i>', array('class' => 'btn btn-danger btn-sm'))." 
                ".anchor(site_url('jadwal/delete/$1'),'<i class="fa fa-trash-o" aria-hidden="true"></i>','class="btn btn-danger btn-sm" onclick="javasciprt: return confirm(\'Hapus data ?\')"'), 'id_jadwal');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_jadwal', $q);
	$this->db->or_like('nama_guru', $q);
	$this->db->or_like('kode_kelas', $q);
    $this->db->or_like('mapel', $q);
	$this->db->or_like('hari', $q);
	    $this->db->or_like('jam_mulai', $q);
	$this->db->or_like('jam_selesai', $q);

	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
       $this->db->like('id_jadwal', $q);
    $this->db->or_like('nama_guru', $q);
    $this->db->or_like('kode_kelas', $q);
    $this->db->or_like('mapel', $q);
    $this->db->or_like('hari', $q);
    $this->db->or_like('jam_mulai', $q);
    $this->db->or_like('jam_selesai', $q);

	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file .php */
/* Location: ./application/models/.php */
/* Please DO NOT modify this information : */
/* Generated by Belicode.com Codeigniter CRUD Generator 2019-10-04 06:32:22 */
/* http://belicode.com */