<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Ujian_model extends CI_Model
{

    public $table = 'tbl_detail_ujian';
    public $id = 'id_ujian';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('tbl_detail_ujian.hari,tbl_detail_ujian.id_ujian,tbl_detail_ujian.kode_mapel,tbl_detail_ujian.kode_kelas,tbl_detail_ujian.tgl_ujian,tbl_detail_ujian.jam_mulai,tbl_detail_ujian.jam_selesai,tbl_detail_ujian.ket,tbl_mapel.mapel');
        $this->datatables->from('tbl_detail_ujian');
    
       
         $this->datatables->join('tbl_mapel','tbl_mapel.kode_mapel=tbl_detail_ujian.kode_mapel');
        $this->datatables->add_column('action',anchor(site_url('ujian/update/$1'),'<i class="fa fa-pencil-square-o" aria-hidden="true"></i>', array('class' => 'btn btn-danger btn-sm'))." 
                ".anchor(site_url('ujian/delete/$1'),'<i class="fa fa-trash-o" aria-hidden="true"></i>','class="btn btn-danger btn-sm" onclick="javasciprt: return confirm(\'Hapus data ?\')"'), 'id_ujian');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_ujian', $q);
	$this->db->or_like('kode_kelas', $q);
    $this->db->or_like('kode_mapel', $q);
	
    $this->db->or_like('tgl_ujian', $q);
	$this->db->or_like('jam_mulai', $q);
	
	$this->db->or_like('jam_selesai', $q);
    $this->db->or_like('ket', $q);

	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_ujian', $q);
    $this->db->or_like('kode_kelas', $q);
        $this->db->or_like('kode_mapel', $q);
   
    $this->db->or_like('tgl_ujian', $q);
    $this->db->or_like('jam_mulai', $q);
    
    $this->db->or_like('jam_selesai', $q);
$this->db->or_like('ket', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file .php */
/* Location: ./application/models/.php */
/* Please DO NOT modify this information : */
/* Generated by Belicode.com Codeigniter CRUD Generator 2019-10-04 06:32:22 */
/* http://belicode.com */